# site
title: Phoemela Ballaran
url: "https://phoemelaballaran.github.io"
favicon: "/assets/sample/ico.png"
g_analytics: UA-12345678-1

# bio
header: PHOEMELA BALLARAN [DATA + DESIGN]
desc: >
  "The commonality between science and art is in trying to see profoundly - to develop strategies of seeing and showing." — Edward Tufte

# posts
date_format: "%Y"
post_title: Story
post_date: Year
post_cat: Genre

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
