# site
title: Phoemela Ballaran
url: "https://phoemelaballaran.github.io"
favicon: "/assets/sample/ico.png"
g_analytics: UA-12345678-1

# bio
header: Phoemela Ballaran
desc: >
  I’m a designer-engineer who aims to contribute in humanizing technology, especially when it comes to the usage of data.
  I'd like to work on projects that shift technology into a form that enriches rather than enslaves. 

# posts
date_format: "%Y"
post_title: Story
post_date: Year
post_cat: Genre

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
